baseurl: /
languageCode: en-us
title: Brady Johnston
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
    - name: Blog
      url: /
    - name: GitHub
      url: https://github.com/bradyajohnston
    - name: Twitter
      url: https://twitter.com/bradyajohnston
    - name: YouTube
      url: https://youtube.com/c/bradyjohnston
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: Brady Johnston's Personal Website.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: tomorrow-night-eighties
  highlightjsVersion: 9.12.0
  logo:
    alt: Headshot
    height: 100
    url: headshot.png
    width: 100
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
